// File generated by flutterfire configure
// To regenerate this file, run: flutterfire configure
// Or manually fill in your Firebase project configuration below

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-TGFR5wnfd8DSZLsm7sm6grp8iCGHh0',
    appId: '1:6001836083:web:420984e9517e32b1c0e346',
    messagingSenderId: '6001836083',
    projectId: 'qauto-dam',
    authDomain: 'qauto-dam.firebaseapp.com',
    storageBucket: 'qauto-dam.firebasestorage.app',
    measurementId: 'G-BNG71MEGK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBbDROBrgg3VjaSLpuBXvKMDwVGFNTG9k',
    appId: '1:6001836083:android:399a01d88883bdf7c0e346',
    messagingSenderId: '6001836083',
    projectId: 'qauto-dam',
    storageBucket: 'qauto-dam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcFPseCYmGI2lGqIGk-CGgavieOKR_B8',
    appId: '1:6001836083:ios:61097f243aa71b97c0e346',
    messagingSenderId: '6001836083',
    projectId: 'qauto-dam',
    storageBucket: 'qauto-dam.firebasestorage.app',
    iosBundleId: 'com.example.qAutoInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcFPseCYmGI2lGqIGk-CGgavieOKR_B8',
    appId: '1:6001836083:ios:61097f243aa71b97c0e346',
    messagingSenderId: '6001836083',
    projectId: 'qauto-dam',
    storageBucket: 'qauto-dam.firebasestorage.app',
    iosBundleId: 'com.example.qAutoInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ-TGFR5wnfd8DSZLsm7sm6grp8iCGHh0',
    appId: '1:6001836083:web:bcbc3c27c18f3d03c0e346',
    messagingSenderId: '6001836083',
    projectId: 'qauto-dam',
    authDomain: 'qauto-dam.firebaseapp.com',
    storageBucket: 'qauto-dam.firebasestorage.app',
    measurementId: 'G-9TT1V21X2Z',
  );

}
